# -*- coding: utf-8 -*-
"""codigo_para_cargar_db_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14uQCZovd052VhgPBmtFrePmX6OnS9VOD
"""

import pandas as pd

# Cargar la base de datos limpia
df = pd.read_csv('base_datos_historica_JJOO_1900_1936.csv')
# Visualizar las primeras filas
df.head()