# -*- coding: utf-8 -*-
"""script ortúzar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gz7SJFkgWNzK0D2htuSNlWOd7LKswiYX
"""

import pandas as pd

!ls

import seaborn as sns # importar la libreria seaborn

olimpicos = pd.read_csv('base de datos general(Hoja1).csv')
olimpicos.head()