# -*- coding: utf-8 -*-
"""codigo_para_cargar_db_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G3-QU2UrHcquhTPP0p_qpi21FryOo0iW
"""

# Cargar la base de datos limpia
# (Asegúrate de subir el archivo CSV al menú de la izquierda en Colab, en el ícono de la carpeta)
df = pd.read_csv('JJOO_1948_1984_Limpia.csv')

# Visualizar las primeras filas de la base de datos
df.head(10)